[[redirects]]
   from = "/social/*"
   to = "/social/[id].html"
   status = 200
   force = true

[[redirects]]
   from = "/*"
   to = "/"
   status = 200

[build]
  command = "npm run build && npm run export"
  publish = "out"